// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASeWthGu4zZTn44Z7bz-fBGKlevnWAyCY',
    appId: '1:554528016013:web:fb71b7243f649bd89c04c4',
    messagingSenderId: '554528016013',
    projectId: 'grocery-app-shakinul',
    authDomain: 'grocery-app-shakinul.firebaseapp.com',
    storageBucket: 'grocery-app-shakinul.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeq1Mh3qOHnlHyuvoaMYUS_tjHgOaK3IQ',
    appId: '1:554528016013:android:7d4e7122efdbaf619c04c4',
    messagingSenderId: '554528016013',
    projectId: 'grocery-app-shakinul',
    storageBucket: 'grocery-app-shakinul.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJyKBghys--PhRocMpzA420D18b0vs8Jo',
    appId: '1:554528016013:ios:6cfc3c5dd44337169c04c4',
    messagingSenderId: '554528016013',
    projectId: 'grocery-app-shakinul',
    storageBucket: 'grocery-app-shakinul.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJyKBghys--PhRocMpzA420D18b0vs8Jo',
    appId: '1:554528016013:ios:6cfc3c5dd44337169c04c4',
    messagingSenderId: '554528016013',
    projectId: 'grocery-app-shakinul',
    storageBucket: 'grocery-app-shakinul.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASeWthGu4zZTn44Z7bz-fBGKlevnWAyCY',
    appId: '1:554528016013:web:ab9d83d6b863550e9c04c4',
    messagingSenderId: '554528016013',
    projectId: 'grocery-app-shakinul',
    authDomain: 'grocery-app-shakinul.firebaseapp.com',
    storageBucket: 'grocery-app-shakinul.firebasestorage.app',
  );
}
